### ISSUE TITLE
Wiki issues

### ISSUE THREAD

**Issue by ColonelBlimp** [pisv/gethandly#2]
Hi,
I've started working through 'step-by-step' guide on the wiki and have found some typos and other issues.  However, I seem unable to clone the wiki do the corrections and make a pull request.

Any help appreciated.

**Comment by pisv** [comment]
Hi,
Thanks for reporting the issue! Unfortunately, there seems to be no way to send pull requests for wiki changes (https://github.community/t/how-to-fork-a-wiki-and-send-a-pr/2006). As a workaround, I have created a clone of the wiki that you can hopefully fork and make a PR against: https://github.com/pisv/gethandly.wiki-playground

**Comment by ColonelBlimp** [comment]
> 
> 
> Hi,
> Thanks for reporting the issue! Unfortunately, there seems to be no way to send pull requests for wiki changes (https://github.community/t/how-to-fork-a-wiki-and-send-a-pr/2006). As a workaround, I have created a clone of the wiki that you can hopefully fork and make a PR against: https://github.com/pisv/gethandly.wiki-playground

Many thanks.
