### ISSUE TITLE
Step Two: Junit Test failure

### ISSUE THREAD

**Issue by ColonelBlimp** [pisv/gethandly#3]
### Issue:
The <code>FooFileTest</code> class fails at the following: <code>assertEquals(0, defs[0].getParameterNames().length);</code>.

### Cause:
<code>
    public Object get(IElement element)

    {

        if (element instanceof IFooModel)

            return modelBody;

        else if (element instanceof IFooProject)

            return projectCache.get(element);

        else

           return null; // Here is the issue

    }
</code>
### Misc:
This also throws an ambiguous error:
<code>f [in test.foo [in Test002]] does not exist</code>

**Comment by pisv** [comment]
Great catch!

This section of the tutorial needs to be rewritten. Some time ago it worked that way, but in version 0.8 the algorithm of element opening has changed (https://bugs.eclipse.org/bugs/show_bug.cgi?id=525394). As a result, this no longer works without the proper cache implementation, introduced at the very end of Step Two.

I'm in the process of preparing the release of Eclipse Handly 1.4, to be released on Jun 17, and will try to address this issue as part of migrating the tutorial to the new version.

Thanks for catching that!

**Comment by pisv** [comment]
Fixed it right away. The fix is also available in https://github.com/pisv/gethandly.wiki-playground
